name: Publish Python üêç distributions üì¶ to GH Releases and PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  create-publish-releases:
    # Assume the tag is of the form vX.Y.Z
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt

      - name: Install pypa/build, setuptools, wheel
        run: pip install build setuptools wheel

      - name: Build a sources and binary
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Autogenerated token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            compass-interface-core v${{ steps.get_version.outputs.VERSION }}
          draft: true

      - name: Upload Asset to GH Releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/compass-interface-core-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_name: compass-interface-core-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_content_type: application/gzip

      - name: TESTING- upload files
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: my-artifact
          path: |
            *

#      - name: Publish distribution üì¶ to Test PyPI
#        uses: pypa/gh-action-pypi-publish@master
#        with:
#          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution üì¶ to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}